###服务注册到eureka地址
eureka:
  instance:
###注册中心的ip地址
    hostname: 127.0.0.1
# 心跳检测检测与续约时间
# 通过这个极端配置实现服务保护的失效
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
           defaultZone: http://${eureka.instance.hostname}:8000/eureka,http://${eureka.instance.hostname}:8100/eureka
###api网关端口号      
server:
  port: 80
###网关名称
spring:
  application:
    name: app-jxin-zuul
  cloud:
    config:
    ####读取后缀
      profile: dev
      ####读取config注册地址
      discovery:
        service-id: app-jxin-config
        enabled: true

###默认服务读取eureka注册服务列表 默认间隔30秒

###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"