###服务启动端口号
server:
  port: 8001
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-jxin-member
    activemq:
      user: admin
      password: admin
      #整合jms测试，安装在别的机器，防火墙和端口号记得开放
      #集群配置
      #spring.activemq.broker-url=failover:(tcp://localhost:61616,tcp://localhost:61617)
      broker-url: http://192.168.99.100:61616
      #下列配置要增加依赖
      pool:
        enabled: true
        max-connections: 100
###服务注册到eureka地址
eureka:
  instance:
###注册中心的ip地址
    hostname: 127.0.0.1
# 心跳检测检测与续约时间
# 通过这个极端配置实现服务保护的失效
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
           defaultZone: http://${eureka.instance.hostname}:8000/eureka,http://${eureka.instance.hostname}:8100/eureka
           
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 30
