###服务启动端口号
server:
  port: 8002
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-jxin-order
###服务注册到eureka地址
eureka:
  instance:
###注册中心的ip地址
    hostname: 127.0.0.1
# 心跳检测检测与续约时间
# 通过这个极端配置实现服务保护的失效
# 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
           defaultZone: http://${eureka.instance.hostname}:8000/eureka,http://${eureka.instance.hostname}:8100/eureka
           
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 30
###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
###指的是建立连接所用的时间，适用于网络状况正常的情况下，服务两端从未连接到连接所用的时间。
 ReadTimeout: 5000
###指的是建立连接后从服务器读取到可用资源所用的时间。
 ConnectTimeout: 5000

###开启Hystrix断路器
feign:
  hystrix:
    enabled: 'true'


#### hystrix禁止服务超时时间，生产调整会5-10s
hystrix:
 command:
   default:
      execution:
       timeout:
        enabled: false