###服务启动端口号
server:
  port: 8004
###服务名称(服务注册到consul名称)
spring:
    application:
        name: app-jxin-member
####consul注册中心地址
    cloud:
      consul:
        host: 192.168.99.100
        port: 8500
        discovery:
          hostname: localhost
